### ISSUE TITLE
run on middlebury dataset

### ISSUE THREAD

**Issue by pannyl** [t-taniai/mc-cnn-chainer#1]
How long dose it take to run demo.py on middlebury dataset. 
It's been processing for 1more hours and it's not done yet. I don't know if that makes sense.

**Comment by t-taniai** [comment]
Thank you for your comment. Are you using a GPU? If using a CPU, then it might take more than an hour. If using a GPU, it will take up to a few minutes (usually a few seconds but some image pairs have large resolutions which require much more compilations)
