### ISSUE TITLE
the size of .acrt file is much smaller than you provided

### ISSUE THREAD

**Issue by Cguffy** [t-taniai/mc-cnn-chainer#3]
The size of .acrt file is much smaller than you provided. What's the difference between a 300M .acrt file and a 800M .acrt file?
Detailed:
I used your mccnn model and get a .bin file. The original images are the following images:
![im0](https://user-images.githubusercontent.com/43436574/95831760-08c9bd00-0d6c-11eb-85e2-575a1b97abcd.png)
![im1](https://user-images.githubusercontent.com/43436574/95831780-10896180-0d6c-11eb-9cdb-59b9f48e1a46.png)
But the file size is 300M, where the size of .acrt file you provided is 800M. How can I get the .acrt file you provided?
The following image is the disparity map generated by my .acrt file and the algorithm you provided, localExpansionStereo:
![result0D07](https://user-images.githubusercontent.com/43436574/95831410-91942900-0d6b-11eb-9b84-b8048020a11a.png)

**Comment by t-taniai** [comment]
Please check if following settings the same 
1. The input image resolutions
2. The parameter of ndisp (disparity range)

**Comment by Cguffy** [comment]
Oh, I used the kitti_fast model to test the mb images, sorry to trouble you.

**Comment by t-taniai** [comment]
Thanks for letting me know.
